apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: manageiq-httpd
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: manageiq-httpd
    template:
      metadata:
        name: manageiq-httpd
        labels:
          name: manageiq-httpd
      spec:
        containers:
        - name: manageiq-httpd
          image: test-httpd/manageiq-httpd:latest
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - pidof
              - httpd
            initialDelaySeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3
        serviceAccountName: miq-httpd
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-httpd
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: test-httpd
    template:
      metadata:
        name: test-httpd
        labels:
          name: test-httpd
      spec:
        containers:
        - name: test-httpd
          image: test-httpd/test-httpd:latest
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - pidof
              - httpd
            initialDelaySeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3
        serviceAccountName: anyuid
